//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 05:54:21 PM IST 
//


package viewmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scores }
     * 
     */
    public Scores createScores() {
        return new Scores();
    }

    /**
     * Create an instance of {@link Scores.Tournament }
     * 
     */
    public Scores.Tournament createScoresTournament() {
        return new Scores.Tournament();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race }
     * 
     */
    public Scores.Tournament.Race createScoresTournamentRace() {
        return new Scores.Tournament.Race();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Wagers }
     * 
     */
    public Scores.Tournament.Race.Wagers createScoresTournamentRaceWagers() {
        return new Scores.Tournament.Race.Wagers();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Results }
     * 
     */
    public Scores.Tournament.Race.Results createScoresTournamentRaceResults() {
        return new Scores.Tournament.Race.Results();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Runners }
     * 
     */
    public Scores.Tournament.Race.Runners createScoresTournamentRaceRunners() {
        return new Scores.Tournament.Race.Runners();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Runners.Horse }
     * 
     */
    public Scores.Tournament.Race.Runners.Horse createScoresTournamentRaceRunnersHorse() {
        return new Scores.Tournament.Race.Runners.Horse();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Runners.Horse.Odds }
     * 
     */
    public Scores.Tournament.Race.Runners.Horse.Odds createScoresTournamentRaceRunnersHorseOdds() {
        return new Scores.Tournament.Race.Runners.Horse.Odds();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Wagers.Wager }
     * 
     */
    public Scores.Tournament.Race.Wagers.Wager createScoresTournamentRaceWagersWager() {
        return new Scores.Tournament.Race.Wagers.Wager();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Results.Horse }
     * 
     */
    public Scores.Tournament.Race.Results.Horse createScoresTournamentRaceResultsHorse() {
        return new Scores.Tournament.Race.Results.Horse();
    }

    /**
     * Create an instance of {@link Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker }
     * 
     */
    public Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker createScoresTournamentRaceRunnersHorseOddsBookmaker() {
        return new Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker();
    }

}
