//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 05:54:21 PM IST 
//


package viewmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tournament" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="race" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="runners">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="horse" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="odds">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="bookmaker">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                   &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                                   &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                                   &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="results">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="horse" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="win" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                               &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                               &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="wagers">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="wager" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="numbers" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="payoff" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                               &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="offAt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="sport" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tournament"
})
@XmlRootElement(name = "scores")
public class Scores {

    @XmlElement(required = true)
    protected List<Scores.Tournament> tournament;
    @XmlAttribute(name = "sport")
    protected String sport;

    /**
     * Gets the value of the tournament property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tournament property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTournament().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Scores.Tournament }
     * 
     * 
     */
    public List<Scores.Tournament> getTournament() {
        if (tournament == null) {
            tournament = new ArrayList<Scores.Tournament>();
        }
        return this.tournament;
    }

    /**
     * Gets the value of the sport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSport() {
        return sport;
    }

    /**
     * Sets the value of the sport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSport(String value) {
        this.sport = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="race" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="runners">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="horse" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="odds">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="bookmaker">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                         &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                                         &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                                         &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="results">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="horse" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="win" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                     &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                     &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="wagers">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="wager" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="numbers" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="payoff" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                                     &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="offAt" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "race"
    })
    public static class Tournament {

        @XmlElement(required = true)
        protected List<Scores.Tournament.Race> race;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "date")
        protected String date;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the race property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the race property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Scores.Tournament.Race }
         * 
         * 
         */
        public List<Scores.Tournament.Race> getRace() {
            if (race == null) {
                race = new ArrayList<Scores.Tournament.Race>();
            }
            return this.race;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="runners">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="horse" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="odds">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="bookmaker">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                               &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                               &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                               &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="results">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="horse" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="win" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                           &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                           &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="wagers">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="wager" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="numbers" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="payoff" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                           &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="offAt" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="datetime" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "runners",
            "odds",
            "results",
            "wagers"
        })
        public static class Race {

            @XmlElement(required = true)
            protected Scores.Tournament.Race.Runners runners;
            @XmlElement(required = true)
            protected Scores.Tournament.Race.Odds odds;
            @XmlElement(required = true)
            protected Scores.Tournament.Race.Results results;
            @XmlElement(required = true)
            protected Scores.Tournament.Race.Wagers wagers;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "time")
            protected String time;
            @XmlAttribute(name = "offAt")
            protected String offAt;
            @XmlAttribute(name = "class")
            protected String clazz;
            @XmlAttribute(name = "datetime")
            protected String datetime;
            @XmlAttribute(name = "id")
            protected String id;

            
            
            
            public Scores.Tournament.Race.Odds getOdds() {
				return odds;
			}

			public void setOdds(Scores.Tournament.Race.Odds odds) {
				this.odds = odds;
			}

			/**
             * Gets the value of the runners property.
             * 
             * @return
             *     possible object is
             *     {@link Scores.Tournament.Race.Runners }
             *     
             */
            public Scores.Tournament.Race.Runners getRunners() {
                return runners;
            }

            /**
             * Sets the value of the runners property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scores.Tournament.Race.Runners }
             *     
             */
            public void setRunners(Scores.Tournament.Race.Runners value) {
                this.runners = value;
            }

            /**
             * Gets the value of the results property.
             * 
             * @return
             *     possible object is
             *     {@link Scores.Tournament.Race.Results }
             *     
             */
            public Scores.Tournament.Race.Results getResults() {
                return results;
            }

            /**
             * Sets the value of the results property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scores.Tournament.Race.Results }
             *     
             */
            public void setResults(Scores.Tournament.Race.Results value) {
                this.results = value;
            }

            /**
             * Gets the value of the wagers property.
             * 
             * @return
             *     possible object is
             *     {@link Scores.Tournament.Race.Wagers }
             *     
             */
            public Scores.Tournament.Race.Wagers getWagers() {
                return wagers;
            }

            /**
             * Sets the value of the wagers property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scores.Tournament.Race.Wagers }
             *     
             */
            public void setWagers(Scores.Tournament.Race.Wagers value) {
                this.wagers = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the time property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTime() {
                return time;
            }

            /**
             * Sets the value of the time property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTime(String value) {
                this.time = value;
            }

            /**
             * Gets the value of the offAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOffAt() {
                return offAt;
            }

            /**
             * Sets the value of the offAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOffAt(String value) {
                this.offAt = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the datetime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatetime() {
                return datetime;
            }

            /**
             * Sets the value of the datetime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatetime(String value) {
                this.datetime = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="horse" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="win" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                 &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                 &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "horse"
            })
            public static class Results {

                @XmlElement(required = true)
                protected List<Scores.Tournament.Race.Results.Horse> horse;

                /**
                 * Gets the value of the horse property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the horse property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getHorse().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Scores.Tournament.Race.Results.Horse }
                 * 
                 * 
                 */
                public List<Scores.Tournament.Race.Results.Horse> getHorse() {
                    if (horse == null) {
                        horse = new ArrayList<Scores.Tournament.Race.Results.Horse>();
                    }
                    return this.horse;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="pos" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="win" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *       &lt;attribute name="place" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *       &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Horse {

                    @XmlAttribute(name = "pos")
                    protected String pos;
                    @XmlAttribute(name = "number")
                    protected String number;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "wgt")
                    protected String wgt;
                    @XmlAttribute(name = "jockey")
                    protected String jockey;
                    @XmlAttribute(name = "win")
                    protected String win;
                    @XmlAttribute(name = "place")
                    protected String place;
                    @XmlAttribute(name = "show")
                    protected String show;
                    @XmlAttribute(name = "id")
                    protected String id;

                    /**
                     * Gets the value of the pos property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getPos() {
                        return pos;
                    }

                    /**
                     * Sets the value of the pos property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setPos(String value) {
                        this.pos = value;
                    }

                    /**
                     * Gets the value of the number property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getNumber() {
                        return number;
                    }

                    /**
                     * Sets the value of the number property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setNumber(String value) {
                        this.number = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the wgt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getWgt() {
                        return wgt;
                    }

                    /**
                     * Sets the value of the wgt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setWgt(String value) {
                        this.wgt = value;
                    }

                    /**
                     * Gets the value of the jockey property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getJockey() {
                        return jockey;
                    }

                    /**
                     * Sets the value of the jockey property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setJockey(String value) {
                        this.jockey = value;
                    }

                    /**
                     * Gets the value of the win property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public String getWin() {
                        return win;
                    }

                    /**
                     * Sets the value of the win property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setWin(String value) {
                        this.win = value;
                    }

                    /**
                     * Gets the value of the place property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public String getPlace() {
                        return place;
                    }

                    /**
                     * Sets the value of the place property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setPlace(String value) {
                        this.place = value;
                    }

                    /**
                     * Gets the value of the show property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public String getShow() {
                        return show;
                    }

                    /**
                     * Sets the value of the show property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setShow(String value) {
                        this.show = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                }

            }
            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "horse"
            })
            public static class Odds {

                @XmlElement(required = true)
                protected List<Scores.Tournament.Race.Odds.Horse> horse;

                
				public List<Scores.Tournament.Race.Odds.Horse> getHorse() {
					return horse;
				}



				public void setHorse(List<Scores.Tournament.Race.Odds.Horse> horse) {
					this.horse = horse;
				}






				/**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Horse {

                    
                    @XmlAttribute(name = "number")
                    protected String number;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "id")
                    protected String id;
                    @XmlElement(required = true)
                    protected Scores.Tournament.Race.Odds.Horse.Bookmakers bookmakers;
                    
                    
                    
                    public Scores.Tournament.Race.Odds.Horse.Bookmakers getBookmakers() {
						return bookmakers;
					}




					public void setBookmakers(
							Scores.Tournament.Race.Odds.Horse.Bookmakers bookmakers) {
						this.bookmakers = bookmakers;
					}




					public String getNumber() {
						return number;
					}




					public void setNumber(String number) {
						this.number = number;
					}




					public String getName() {
						return name;
					}




					public void setName(String name) {
						this.name = name;
					}




					public String getId() {
						return id;
					}




					public void setId(String id) {
						this.id = id;
					}




				@XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "bookmaker")
                public static class Bookmakers {
                	
                	@XmlElement(required = true)
                    protected List<Scores.Tournament.Race.Odds.Horse.Bookmakers.Bookmaker> bookmaker;
              
                	
                	

                	public List<Scores.Tournament.Race.Odds.Horse.Bookmakers.Bookmaker> getBookmaker() {
						return bookmaker;
					}




					public void setBookmaker(
							List<Scores.Tournament.Race.Odds.Horse.Bookmakers.Bookmaker> bookmaker) {
						this.bookmaker = bookmaker;
					}




				@XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Bookmaker {

                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "odd")
                    protected String odd;
                    @XmlAttribute(name = "bookmaker_id")
                    protected String bookmakerId;
                    @XmlAttribute(name = "odd_id")
                    protected String oddId;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the odd property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getOdd() {
                        return odd;
                    }

                    /**
                     * Sets the value of the odd property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setOdd(String value) {
                        this.odd = value;
                    }

                    /**
                     * Gets the value of the bookmakerId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getBookmakerId() {
                        return bookmakerId;
                    }

                    /**
                     * Sets the value of the bookmakerId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setBookmakerId(String value) {
                        this.bookmakerId = value;
                    }

                    /**
                     * Gets the value of the oddId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getOddId() {
                        return oddId;
                    }

                    /**
                     * Sets the value of the oddId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setOddId(String value) {
                        this.oddId = value;
                    }

                }
                
                
              }  
             
            }    
                
            }

            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="horse" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="odds">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="bookmaker">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                     &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                                     &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                                     &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "horse"
            })
            public static class Runners {

                @XmlElement(required = true)
                protected List<Scores.Tournament.Race.Runners.Horse> horse;

                /**
                 * Gets the value of the horse property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the horse property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getHorse().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Scores.Tournament.Race.Runners.Horse }
                 * 
                 * 
                 */
                public List<Scores.Tournament.Race.Runners.Horse> getHorse() {
                    if (horse == null) {
                        horse = new ArrayList<Scores.Tournament.Race.Runners.Horse>();
                    }
                    return this.horse;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="odds">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="bookmaker">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                           &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                           &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                           &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="wgt" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="jockey" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "odds"
                })
                public static class Horse {

                    @XmlElement(required = true)
                    protected Scores.Tournament.Race.Runners.Horse.Odds odds;
                    @XmlAttribute(name = "number")
                    protected String number;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "age")
                    protected String age;
                    @XmlAttribute(name = "wgt")
                    protected String wgt;
                    @XmlAttribute(name = "jockey")
                    protected String jockey;
                    @XmlAttribute(name = "id")
                    protected String id;

                    /**
                     * Gets the value of the odds property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Scores.Tournament.Race.Runners.Horse.Odds }
                     *     
                     */
                    public Scores.Tournament.Race.Runners.Horse.Odds getOdds() {
                        return odds;
                    }

                    /**
                     * Sets the value of the odds property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Scores.Tournament.Race.Runners.Horse.Odds }
                     *     
                     */
                    public void setOdds(Scores.Tournament.Race.Runners.Horse.Odds value) {
                        this.odds = value;
                    }

                    /**
                     * Gets the value of the number property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getNumber() {
                        return number;
                    }

                    /**
                     * Sets the value of the number property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setNumber(String value) {
                        this.number = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the age property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAge() {
                        return age;
                    }

                    /**
                     * Sets the value of the age property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAge(String value) {
                        this.age = value;
                    }

                    /**
                     * Gets the value of the wgt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getWgt() {
                        return wgt;
                    }

                    /**
                     * Sets the value of the wgt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setWgt(String value) {
                        this.wgt = value;
                    }

                    /**
                     * Gets the value of the jockey property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getJockey() {
                        return jockey;
                    }

                    /**
                     * Sets the value of the jockey property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setJockey(String value) {
                        this.jockey = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="bookmaker">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *                 &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *                 &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *                 &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "bookmaker"
                    })
                    public static class Odds {

                        @XmlElement(required = true)
                        protected Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker bookmaker;

                        /**
                         * Gets the value of the bookmaker property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker }
                         *     
                         */
                        public Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker getBookmaker() {
                            return bookmaker;
                        }

                        /**
                         * Sets the value of the bookmaker property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker }
                         *     
                         */
                        public void setBookmaker(Scores.Tournament.Race.Runners.Horse.Odds.Bookmaker value) {
                            this.bookmaker = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *       &lt;attribute name="odd" type="{http://www.w3.org/2001/XMLSchema}int" />
                         *       &lt;attribute name="bookmaker_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                         *       &lt;attribute name="odd_id" type="{http://www.w3.org/2001/XMLSchema}int" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        

                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "")
                            public static class Bookmaker {

                                @XmlAttribute(name = "name")
                                protected String name;
                                @XmlAttribute(name = "odd")
                                protected String odd;
                                @XmlAttribute(name = "bookmaker_id")
                                protected String bookmakerId;
                                @XmlAttribute(name = "odd_id")
                                protected String oddId;

                                /**
                                 * Gets the value of the name property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getName() {
                                    return name;
                                }

                                /**
                                 * Sets the value of the name property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setName(String value) {
                                    this.name = value;
                                }

                                /**
                                 * Gets the value of the odd property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public String getOdd() {
                                    return odd;
                                }

                                /**
                                 * Sets the value of the odd property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public void setOdd(String value) {
                                    this.odd = value;
                                }

                                /**
                                 * Gets the value of the bookmakerId property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public String getBookmakerId() {
                                    return bookmakerId;
                                }

                                /**
                                 * Sets the value of the bookmakerId property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public void setBookmakerId(String value) {
                                    this.bookmakerId = value;
                                }

                                /**
                                 * Gets the value of the oddId property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public String getOddId() {
                                    return oddId;
                                }

                                /**
                                 * Sets the value of the oddId property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Integer }
                                 *     
                                 */
                                public void setOddId(String value) {
                                    this.oddId = value;
                                }

                            }  
                            

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="wager" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="numbers" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="payoff" type="{http://www.w3.org/2001/XMLSchema}double" />
             *                 &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "wager"
            })
            public static class Wagers {

                @XmlElement(required = true)
                protected List<Scores.Tournament.Race.Wagers.Wager> wager;

                /**
                 * Gets the value of the wager property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the wager property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getWager().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Scores.Tournament.Race.Wagers.Wager }
                 * 
                 * 
                 */
                public List<Scores.Tournament.Race.Wagers.Wager> getWager() {
                    if (wager == null) {
                        wager = new ArrayList<Scores.Tournament.Race.Wagers.Wager>();
                    }
                    return this.wager;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="numbers" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="payoff" type="{http://www.w3.org/2001/XMLSchema}double" />
                 *       &lt;attribute name="pool" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Wager {

                    @XmlAttribute(name = "type")
                    protected String type;
                    @XmlAttribute(name = "numbers")
                    protected String numbers;
                    @XmlAttribute(name = "payoff")
                    protected String payoff;
                    @XmlAttribute(name = "pool")
                    protected String pool;

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the numbers property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNumbers() {
                        return numbers;
                    }

                    /**
                     * Sets the value of the numbers property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNumbers(String value) {
                        this.numbers = value;
                    }

                    /**
                     * Gets the value of the payoff property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Double }
                     *     
                     */
                    public String getPayoff() {
                        return payoff;
                    }

                    /**
                     * Sets the value of the payoff property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Double }
                     *     
                     */
                    public void setPayoff(String value) {
                        this.payoff = value;
                    }

                    /**
                     * Gets the value of the pool property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPool() {
                        return pool;
                    }

                    /**
                     * Sets the value of the pool property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPool(String value) {
                        this.pool = value;
                    }

                }

            }

        }

    }

}
